### ISSUE TITLE
Support import function

### ISSUE THREAD

**Issue by ntucker** [aackerman/circular-dependency-plugin#13]
Here in webpack 2: https://webpack.js.org/guides/code-splitting-import/
Spec: https://github.com/tc39/proposal-dynamic-import

**Comment by aackerman** [comment]
Are you running into an error when attempting to use a dynamic import? I'm unclear on what is preventing this from being used right now.

**Comment by ntucker** [comment]
Sorry, I don't know why I was having an issue before but it seems to be working now. I'll reopen if I have repro but I think it just entered a weird state.

Thanks for getting back to me! :)
