### ISSUE TITLE
better messaging

### ISSUE THREAD

**Issue by calvinmetcalf** [aackerman/circular-dependency-plugin#15]
it might be helpful to update the messaging that this plugin has when it detects a circular-dependency as some users are seeing the errors in dependent modules and reporting them, I can create a pull that notes that a circular dependency isn't an error by itself or some such

see react-bootstrap/react-bootstrap#2147, nodejs/readable-stream#280, and unshiftio/url-parse#49

**Comment by aackerman** [comment]
@calvinmetcalf please do. I believe the default is warnings and you have to opt-in to errors, but I can see from your references that there have been some misunderstandings about how this project is intended to be used.

**Comment by jedmao** [comment]
I think a simple `logLevel` option might make everyone happy.
