### ISSUE TITLE
Type definitions for TypeScript

### ISSUE THREAD

**Issue by levsthings** [aackerman/circular-dependency-plugin#17]
Would there be any interest in adding a type definition file to the repo? I have a type definition ready for this package.

**Comment by aackerman** [comment]
Can you post it as part of a comment? I'm unclear on what benefit a TS/Flow user would get from it for this project.

**Comment by levsthings** [comment]
Well, you can't just use a module without type definitions in a TypeScript projects, you get errors.

So we either
1- Add local definitions
2- Submit definitions to the module itself.
3- Submit definitions to [this repository](https://github.com/DefinitelyTyped/DefinitelyTyped).


```typescript
declare module 'circular-dependency-plugin' {
  import { Compiler, Plugin } from 'webpack'

  interface CircularDependencyPluginOptions {
    exclude?: RegExp
    failOnError?: boolean
  }

  class CircularDependencyPlugin implements Plugin {
    constructor(options?: CircularDependencyPluginOptions)
    apply(compiler: Compiler): void
  }

  namespace CircularDependencyPlugin { }

  export = CircularDependencyPlugin
}
```

**Comment by aackerman** [comment]
> but it involves adding tests as well

Can you explain more about what you mean by this?

**Comment by aackerman** [comment]
Aside from that yes, I would accept a PR for adding the types. I assume in an `index.d.ts` file?

**Comment by levsthings** [comment]
Sorry if I wasn't clear in my initial message. 

> Can you explain more about what you mean by this?

The testing part was for this option:

> 3- Submit definitions to [this repository](https://github.com/DefinitelyTyped/DefinitelyTyped).

According to their contribution guidelines, a contributor has to submit the types along with some tests. If someone wrote those tests and add the definition file to DefinitelyTyped, then TS users are able to get these via: 
`npm install circular-dependency-plugin`
`npm install @types/circular-dependency-plugin`

The benefit of adding the definitions there is that the types will have their own versioning so it'll be easy for community to update them as your API changes without knocking on your.

> 2- Submit definitions to the module itself.

This option involves just adding the `index.d.ts` file to your repo, no tests are not mandatory. The definitions will be pulled automatically and the TS compiler will be happy. The downside of this method is if your API changes, you should update the definition file yourself as the maintainer of the module.

I'm not saying you should do this or do the other, I'm just bringing the definitions in case anyone is interested in maintaining them or maybe submitting them to DefinitelyTyped. :)

**Comment by aackerman** [comment]
I was just unclear about what tests could be created for a type definition file.

Please do go ahead and submit a PR to add the type definitions.

**Comment by aackerman** [comment]
I'm going to close this as it's not something I'm willing to take on myself, but I would still accept a PR.

**Comment by jeremejevs** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33952
