### ISSUE TITLE
Detection with the ModuleConcatenationPlugin

### ISSUE THREAD

**Issue by gpoitch** [aackerman/circular-dependency-plugin#19]
When using the `webpack.optimize.ModuleConcatenationPlugin` introduced in webpack 3, it appears that this plugin in unable to detect a lot of circular dependencies.

When removing ModuleConcatenationPlugin, it outputs more warnings.

**Comment by aackerman** [comment]
Thanks for the info, I haven't done much testing with Webpack 3. I'll look into it.

**Comment by aackerman** [comment]
@gpoitch I believe these plugins are usually run in order, when you were using the `ModuleConcatenationPlugin` was it before the `CircularDependencyPlugin`?

**Comment by gpoitch** [comment]
I tested both before and after.  I believe the issue is that this plugin runs on the 'done' plugin event, at which point the [ModuleConcatenationPlugin](https://github.com/webpack/webpack/blob/f75418f6683af5e7cab86d67d896bf5001075836/lib/optimize/ModuleConcatenationPlugin.js) has already did its thing (merged/hoisted dependencies).  

It makes sense that _some_ circular dependencies could actually be eliminated by what the `ModuleConcatenationPlugin` does, but not all of them. I still saw some `undefined` imports and no warning from this plugin.

**Comment by gpoitch** [comment]
@aackerman Here's a minimal reproduction: https://github.com/gpoitch/webpack-circ-dep-bug

**Comment by aackerman** [comment]
@gpoitch thanks, I imagine this will help a lot in addressing this issue.

**Comment by aackerman** [comment]
This should be fixed in version 4.1.0

**Comment by gpoitch** [comment]
👏 thanks!
