### ISSUE TITLE
Option to exclude circular dependencies chains including a module

### ISSUE THREAD

**Issue by vkammerer** [aackerman/circular-dependency-plugin#20]
Hello,

Thank you for the great plugin!

I have a module 'moduleA' in my project which I would like to exclude from the circular dependency check. I can use the "exclude" option":
```javascript
{
  exclude: /moduleA/
}
```

But I would also like to be able to exclude any circular dependency traversing 'moduleA'... For now, the "exclude" option only tests the resource of the module being compiled, but doesn't test on the chain of the circular dependency.

Would it be possible to add this option? something similar to "excludeIfTraverses"?
```javascript
{
  excludeIfTraverses: /moduleA/
}
```

**Comment by aackerman** [comment]
Hi, @vkammerer. Can you explain further? 

You're saying that exclude will ignore something like: 

`moduleA -> moduleB -> moduleA` 

but not 

`moduleB -> moduleA -> moduleC -> moduleA`?

**Comment by vkammerer** [comment]
Yes, with your last line being
```javascript
moduleB -> moduleA -> moduleC -> moduleB
```
Isn't it how you designed the option?

**Comment by aackerman** [comment]
I've published version 4 that allows a consumer to provide an `onDetected` option. This will allow you to accomplish the behavior you want. I'm going to go ahead and close this.

**Comment by vkammerer** [comment]
ok great thank you!

**Comment by Whiskeyi** [comment]
I also have the same problem, "onDetected" cannot satisfy me because it can only control the output.
