### ISSUE TITLE
Clarification on `exclude` option

### ISSUE THREAD

**Issue by j3tan** [aackerman/circular-dependency-plugin#25]
Wonderful plugin, just wanted some documentation/clarification on the `exclude` option. I had to read the source to figure out passing `onDetected` would still fire for `node_modules` even with `exclude: /node_modules/` set. i.e. I just copy and pasted the example code and nothing was getting excluded. Alternatively, just move the `exclude` test above the `onDetected` handler

Version 4.2.0

Thanks!

**Comment by j3tan** [comment]
Whoops, just realized it is commented in the example. Maybe have separate examples?

**Comment by oomathias** [comment]
Same here, I got confused when defining `onDetected`.
2 distinct examples would be better for those, like me, who didn't read everything 🤦‍♂️

**Comment by aackerman** [comment]
I went ahead and split this up in 4.2.1 to make it even more clear

**Comment by vikasraj789** [comment]
version: 4.4.0
The issue of exclude option not being honoured when onDetected is available still exists.
Below is the configuration:
```
new CircularDependencyPlugin({
        exclude: /(node_modules|bower_components)/,
        // `onDetected` is called for each module that is cyclical
        onDetected({ module: webpackModuleRecord, paths, compilation }) {
          // `paths` will be an Array of the relative module paths that make up the cycle
          // `module` will be the module record generated by webpack that caused the cycle
          compilation.errors.push(new Error(paths.join(' -> ')));
        }
      }),
```

**Comment by aackerman** [comment]
`onDetected` is for advanced usage, you're on your own for everything aside from detection. It's very easy to exclude modules you don't want to see.

```js
new CircularDependencyPlugin({
  onDetected({ module: webpackModuleRecord, paths, compilation }) {
    if (!/(node_modules|bower_components)/.test(webpackModuleRecord.resource)) {
      compilation.errors.push(new Error(paths.join(' -> ')));
    }
  }
})
```

**Comment by LoicAG** [comment]
First of all, thanks a lot for this module!
Regarding the `exclude` / `onDetected` confusion: is there any chance you could also put the `exclude` logic before `onDetected` gets fired on version 4 of the module?

**Comment by abirmingham** [comment]
For posterity - it appears that `exclude` logic is now executed prior to firing `onDetected`. I am using `circular-dependency-plugin@5.2.0` and saw circular dependency errors reduced from 100 to 96 by adding `exclude: /node_modules/,` to the following configuration:

**Configuration**
```javascript
        new CircularDependencyPlugin({
            failOnError: true,
            onStart({ compilation }) {
                circularDepCycles = [];
            },
            onDetected({ module: webpackModuleRecord, paths, compilation }) {
                circularDepCycles.push(
                    new Error(
                        `Circular dependency detected:\n${paths.join(' -> ')}`,
                    ),
                );
            },
            onEnd({ compilation }) {
                const count = circularDepCycles.length;
                if (count > MAX_CIRCULAR_DEP_CYCLES) {
                    circularDepCycles
                        .slice(MAX_CIRCULAR_DEP_CYCLES)
                        .forEach(error => {
                            compilation.errors.push(error);
                        });
                    compilation.warnings.push(
                        new Error(
                            `Circular dependency count exceeds allowed ` +
                                `threshold ` +
                                `(${count} > ${MAX_CIRCULAR_DEP_CYCLES})`,
                        ),
                    );
                }
            },
        }),
```

(Note that I believe that `failOnError` is ignored here due to the presence of `onDetected` - it just so happened to be set when I ran these tests)
