### ISSUE TITLE
Changelog !! No info about changes

### ISSUE THREAD

**Issue by petrleocompel** [aackerman/circular-dependency-plugin#26]
I had version 3.0.0. Now version 4.2.1 is out. I want to upgrade but there is no info what have been done.
No info about breaking changes...
In your releases is nothing. And you dont have even changelog. 
Only info is in your commits. But commit is not a changelog. 

Please start making CHANGELOG - http://keepachangelog.com

**Comment by emilio-martinez** [comment]
@aackerman Ping.

I think this is fairly important. Not that every detail is needed in the changelog, but at a minimum, it would be great to know what the breaking changes are—if any. As mentioned above, it's unclear what the major version bump was due to.

**Comment by elijahdorman** [comment]
A changelog would be amazing!
