### ISSUE TITLE
TypeError: Cannot read property 'compilation' of undefined

### ISSUE THREAD

**Issue by 0xc0d3r** [aackerman/circular-dependency-plugin#38]
I'm trying to integrate circular-dependency-plugin to see the circular imports in storybook's `webpack.config.js`. Here is my webpack config

`webpakc.config.js`
```
// webpack.config.js
const CircularDependencyPlugin = require('circular-dependency-plugin')
const genDefaultConfig = require('@storybook/react-native/dist/server/config/defaults/webpack.config.js')

module.exports = (baseConfig, env) => {
  const defaultConfig = genDefaultConfig(baseConfig, env)
  defaultConfig.plugins.push(
    new CircularDependencyPlugin({
      // exclude detection of files based on a RegExp
      exclude: /node_modules/,
      // add errors to webpack instead of warnings
      failOnError: true
    })
  )
  return defaultConfig
}
```

After running `npm run storybook`, we are getting this error. `TypeError: Cannot read property 'compilation' of undefined`.

storybook version: 3.3.15.

Thanks!

**Comment by aackerman** [comment]
What versions of the plugin and webpack are you using?

**Comment by 0xc0d3r** [comment]
circular-dependency-plugin version: `5.0.2`
storybook version: `3.3.15`

storybook is internally using webpack version of `3.10.0`
