### ISSUE TITLE
Integration with Jenkins CI

### ISSUE THREAD

**Issue by sudheerj** [aackerman/circular-dependency-plugin#40]
I'am looking for the usage and implementation of this plugin in Vue project. Is there any issue to integrate this plugin for Jenkins CI build

**Comment by aackerman** [comment]
There shouldn't be any issue with integrating this plugin with a Jenkins CI build. 

The plugin is expected to error in the presence of circular dependencies with respect to the plugin configuration options, and that should cause webpack to fail and the build to fail.

**Comment by sudheerj** [comment]
I hope configuring this plugin with in webpack.dev.config.js file will make it available to Jenkins CI build similar to other plugins. We are going to apply warnings instead errors using the options.

**Comment by aackerman** [comment]
@sudheerj 

1. There are no current plans to include visualization, I think other project handle visualizing webpack much better than I could.
2. Yes, you can provide the `exclude` option with a RegExp to define which files to exclude, it's common to exclude `node_modules`. The README has a good example.
