### ISSUE TITLE
still has warnning when excluded

### ISSUE THREAD

**Issue by tjx666** [aackerman/circular-dependency-plugin#52]
Although I set /node_modules/ to exclude node_modules detection, there are still some warnings...

![screenshot_2020-01-26_11-39-00](https://user-images.githubusercontent.com/41773861/73130421-eef81680-4032-11ea-910c-f28742689f06.png)

**Comment by aackerman** [comment]
The warning you posted doesn't appear to be generated by this library. Warnings will be prefixed with `Circular dependency detected` and it will show the full circular path. In your screenshot I see `Critical dependency: ...` so I'm going to go ahead and close this. I wish you luck in fixing this issue on your end. Have a good day!
