### ISSUE TITLE
Webpack 5 

### ISSUE THREAD

**Issue by Franatec** [aackerman/circular-dependency-plugin#69]
Related https://github.com/aackerman/circular-dependency-plugin/issues/60

**Setup**

I'm migrating my project from Webpack 4 to 5. Circular-dependency-plugin was running without errors in Webpack 4, in 5 index.js imports are being marked as circular dependency errors. 

```
| Package                    | Version |
| -------------------------- | ------- |
| webpack                    | 5.24.4  |
| circular-dependency-plugin | 5.2.2   |
```

**package-lock.json**

```
    "circular-dependency-plugin": {
      "version": "5.2.2",
      "resolved": "https://registry.npmjs.org/circular-dependency-plugin/-/circular-dependency-plugin-5.2.2.tgz",
      "integrity": "sha512-g38K9Cm5WRwlaH6g03B9OEz/0qRizI+2I7n+Gz+L5DxXJAPAiWQvwlYNm1V1jkdpUv95bOe/ASm2vfi/G560jQ==",
      "dev": true
    }

    "webpack-dev-server": {
      "version": "3.11.2",
      "resolved": "https://registry.npmjs.org/webpack-dev-server/-/webpack-dev-server-3.11.2.tgz",
      "integrity": "sha512-A80BkuHRQfCiNtGBS1EMf2ChTUs0x+B3wGDFmOeT4rmJOHhHTCH2naNxIHhmkr0/UillP4U3yeIyv1pNp+QDLQ==",
      "dev": true
    }

    "webpack": {
      "version": "5.24.4",
      "resolved": "https://registry.npmjs.org/webpack/-/webpack-5.24.4.tgz",
      "integrity": "sha512-RXOdxF9hFFFhg47BryCgyFrEyyu7Y/75/uiI2DoUiTMqysK+WczVSTppvkR47oZcmI/DPaXCiCiaXBP8QjkNpA==",
      "dev": true
    }
```

I'm pretty sure the following is not a circular dependency, but I'd like some feedback. I may have been handling import/export wrong all this time.

**Here's a very simplistic view:**

**Folder structure:**
```
folder1
  file1a.js
  file1b.js
  index.js
```

**file1a**
```
  export default () => something_to_return
```

**file1b**

```
  import { file1a } from './'
  export default () => file1a()
```

**index.js**
```
  import file1a from './file1a.js'
  import file2a from './file2a.js'
  export { file1a, file2a }
```

**message**
```
ERROR in Circular dependency detected:
file1b.js -> index.js -> file1b.js
```

**Comment by aackerman** [comment]
I haven't seen this specific issue before but I would assume it goes away if your import is in `file1b` is changed to `import { file1a } from './index'`. I'm not sure how ` import ... from './'` is supposed to work

**Comment by Franatec** [comment]
@aackerman, unfortunately using `./index` makes no difference.

Import from './' just references the folder which by default looks at the `index.js` first - so just shorthand for `./index`, really.

**gtagEvents.js**
```
export const sendPageView...
```

**RouteAnalytics.jsx**
```
import { sendPageView } from './index.js'
...
export default RouteAnalytics
```

**index.js**
```
import { sendPageView } from './gtagEvents'
import RouteAnalytics from './RouteAnalytics'

export { RouteAnalytics, sendPageView }
```

**output**
```
WARNING in Circular dependency detected:
src\components\common\Analytics\index.js -> src\components\common\Analytics\RouteAnalytics.jsx -> src\components\common\Analytics\index.js
```

**Comment by aackerman** [comment]
Maybe I'm misunderstanding your question but your latest example looks circular to me, it wouldn't be if `RouteAnalytics` imported `gtagEvents` instead of `index`

**Comment by ghost** [comment]
@aackerman, I've been using it like this for years, but looks like you're right. Even though it works, it may be causing other issues. Looks like I have a lot of refactoring to do -- I use this format all over my project. Here's a related [stackexchange link](https://stackoverflow.com/questions/49116860/webpack-es6-modules-circular-dependencies-when-using-index-files) for anybody else who runs into this issue.

Solution for my issue then would be to import files in the same folder from their own exports, instead of their shared index.js file.
