### ISSUE TITLE
@types/circular-dependency-plugin is not compatible with Webpack 5

### ISSUE THREAD

**Issue by dko-slapdash** [aackerman/circular-dependency-plugin#79]
Hi.

@types/circular-dependency-plugin has a different webpack version dependency, so Compiler type is incompatible:

```
      Type '(compiler: import("/Users/d/Documents/git/slapdash/node_modules/@types/circular-dependency-plugin/node_modules/@types/webpack/index").Compiler) => void' is not assignable to type '(compiler: import("/Users/d/Documents/git/slapdash/node_modules/webpack/types").Compiler) => void'.
        Types of parameters 'compiler' and 'compiler' are incompatible.
          Type 'Compiler' is missing the following properties from type 'Compiler': _pluginCompat, _plugins, plugin, apply, and 17 more.
```

**Comment by wdfinch** [comment]
Also getting this

**Comment by gbiryukov** [comment]
Typings [should support `@5` ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/circular-dependency-plugin/package.json#L4)

If you getting this error this means your lock file pinned previous minor version of webpack as dependency for tis plugin resulting in types incompatibility.

You can use tool like `yarn-deduplicate` to fix your lock file and sync version back

**Comment by aackerman** [comment]
The project `@types/circular-dependency-plugin` is supported by a different maintainer
