### ISSUE TITLE
Fast builds during development

### ISSUE THREAD

**Issue by niksrc** [aackerman/circular-dependency-plugin#90]
`CircularDependencyPlugin` is currently too expensive to run during development, especially during hot reloads where it can take more than ~50% of the total build time.
Reference: #62 / https://github.com/angular/angular-cli/issues/19794

`optimizeModules` hook is currently used to support setups with `ModuleConcatenationPlugin` enabled. In most setups though, `ModuleConcatenationPlugin` is disabled during development which means we can move the processing at the end of the compilation process, and achieve super-fast hot reloads.

Here's the required change: https://github.com/niksrc/circular-dependency-plugin/blob/4aa03d124943ccae00b7624696318c155acc5709/index.js#L17-L33 to make it work.

This is similar to the way the plugin used to work before `ModuleConcatenationPlugin` support was added: https://github.com/aackerman/circular-dependency-plugin/commit/cce7601313959cda092b7be8379e9ec4aa382ee1

> I recommend not using this in dev mode where you want/need fast compilation, 6 seconds is brutal enough.
> 
> I have no strong intentions to make this plugin faster because I recommend it to be used to trigge errors in CI and if the duration is 12 seconds in CI, that's not important enough to micro-optimize.
> 
> _Originally posted by @aackerman in https://github.com/aackerman/circular-dependency-plugin/issues/62#issuecomment-721870397_

The tradeoff of leaving this enabled in dev mode still stands as devs would be able to spot these issues immediately and avoid dumping hours of work later on (when they open a PR).

@aackerman I can open a PR for this if you feel this is an acceptable fix.

**Comment by OliverJAsh** [comment]
@niksrc Where did you land on this?

**Comment by niksrc** [comment]
Unfortunately, the above design didn't work. I was able to make it go faster by running the checks once every 2 minutes:
https://github.com/gathertown/circular-dependency-plugin#differences-from-the-upstream-repo
